In [ ]:
!pip install nltk

Requirement already satisfied: nltk in /usr/local/lib/python3.6/dist-packages (3.2.5)
Requirement already satisfied: six in /usr/local/lib/python3.6/dist-packages (from nltk) (1.15.0)

In [13]:
!pip install twarc tqdm

Collecting twarc
  Downloading https://files.pythonhosted.org/packages/ad/98/bedad6cd82b25cb58cedea72103c8c17eab1251b9cbf8a9f3b695460b77a/twarc-1.12.1.tar.gz
Requirement already satisfied: tqdm in /usr/local/lib/python3.6/dist-packages (4.41.1)
Requirement already satisfied: pytest in /usr/local/lib/python3.6/dist-packages (from twarc) (3.6.4)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.6/dist-packages (from twarc) (2.8.1)
Requirement already satisfied: requests_oauthlib in /usr/local/lib/python3.6/dist-packages (from twarc) (1.3.0)
Requirement already satisfied: atomicwrites>=1.0 in /usr/local/lib/python3.6/dist-packages (from pytest->twarc) (1.4.0)
Requirement already satisfied: pluggy<0.8,>=0.5 in /usr/local/lib/python3.6/dist-packages (from pytest->twarc) (0.7.1)
Requirement already satisfied: more-itertools>=4.0.0 in /usr/local/lib/python3.6/dist-packages (from pytest->twarc) (8.6.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.6/dist-packages (from pytest->twarc) (51.3.3)
Requirement already satisfied: attrs>=17.4.0 in /usr/local/lib/python3.6/dist-packages (from pytest->twarc) (20.3.0)
Requirement already satisfied: py>=1.5.0 in /usr/local/lib/python3.6/dist-packages (from pytest->twarc) (1.10.0)
Requirement already satisfied: six>=1.10.0 in /usr/local/lib/python3.6/dist-packages (from pytest->twarc) (1.15.0)
Requirement already satisfied: requests>=2.0.0 in /usr/local/lib/python3.6/dist-packages (from requests_oauthlib->twarc) (2.23.0)
Requirement already satisfied: oauthlib>=3.0.0 in /usr/local/lib/python3.6/dist-packages (from requests_oauthlib->twarc) (3.1.0)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.6/dist-packages (from requests>=2.0.0->requests_oauthlib->twarc) (3.0.4)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.6/dist-packages (from requests>=2.0.0->requests_oauthlib->twarc) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.6/dist-packages (from requests>=2.0.0->requests_oauthlib->twarc) (2020.12.5)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.6/dist-packages (from requests>=2.0.0->requests_oauthlib->twarc) (1.24.3)
Building wheels for collected packages: twarc
  Building wheel for twarc (setup.py) ... done
  Created wheel for twarc: filename=twarc-1.12.1-cp36-none-any.whl size=25378 sha256=1067d83acdabda943179403c0bcaa25155ce921600581455376539bd10dc4b3c
  Stored in directory: /root/.cache/pip/wheels/27/23/c9/02e0e8e88c080696be86b53a15252abeb03ad85d84cb8870b8
Successfully built twarc
Installing collected packages: twarc
Successfully installed twarc-1.12.1

In [17]:
!twarc configure

Twarc needs to know a few things before it can talk to Twitter on your behalf.

You already have these application keys in your config /root/.twarc

consumer key: VMTYhsB6VxUyRdOKpyq603lA1
consumer secret: TPRBE7ozjeOpEPKMQsM1xw94M5XU2FvpnqjPHf4hlDAdBB51f2

Would you like to use those for your new profile? [y/n] y

How would you like twarc to obtain your user keys?

1) generate access keys by visiting Twitter
2) manually enter your access token and secret

Please enter your choice [1/2] 2
Enter your Access Token: 1326885449978187776-x5A1ccTtCTmujMUXFe2UtO5RoJUjWl
Enter your Access Token Secret: zeW0kUhLpuJruFcS1hpXfPERqj9iIKAta45fkBnfjWZgN

The credentials for default have been saved to your configuration file at /root/.twarc

✨ ✨ ✨  Happy twarcing! ✨ ✨ ✨

In [19]:
!python3 "/content/drive/MyDrive/HoyaHacks 2021/hydrate.py"

Hydrating /content/drive/MyDrive/HoyaHacks 2021/2020-10/2020-10-23.csv
2020-10-23.csv
Hydrating 3271 tweets
 63% 2048/3271 [00:11<00:06, 178.51it/s]
Hydrating /content/drive/MyDrive/HoyaHacks 2021/2020-10/2020-10-24.csv
2020-10-24.csv
Hydrating 25045 tweets
 62% 15479/25045 [01:35<00:59, 161.88it/s]
Hydrating /content/drive/MyDrive/HoyaHacks 2021/2020-10/2020-10-25.csv
2020-10-25.csv
Hydrating 57640 tweets
 63% 36440/57640 [03:43<02:09, 163.41it/s]

In [21]:
!pip install jsonlines

Collecting jsonlines
  Downloading https://files.pythonhosted.org/packages/d4/58/06f430ff7607a2929f80f07bfd820acbc508a4e977542fefcc522cde9dff/jsonlines-2.0.0-py3-none-any.whl
Installing collected packages: jsonlines
Successfully installed jsonlines-2.0.0

In [24]:
import jsonlines


with jsonlines.open('/content/drive/MyDrive/HoyaHacks 2021/2020-10/2020-10-23.jsonl.gz') as f:

    for line in f.iter():

        print(line)

UnicodeDecodeError: ignored

In [28]:
import gzip
with open('/content/drive/MyDrive/HoyaHacks 2021/2020-10/2020-10-23.jsonl.gz', 'rb') as fd:
    gzip_fd = gzip.GzipFile(fileobj=fd)
    destinations = pd.read_json(gzip_fd, lines = True)
destinations

,created_at,id,id_str,full_text,truncated,display_text_range,entities,source,in_reply_to_status_id,in_reply_to_status_id_str,in_reply_to_user_id,in_reply_to_user_id_str,in_reply_to_screen_name,user,geo,coordinates,place,contributors,is_quote_status,retweet_count,favorite_count,favorited,retweeted,possibly_sensitive,lang,quoted_status_id,quoted_status_id_str,quoted_status_permalink,quoted_status,extended_entities
0,2020-10-23 17:00:06+00:00,1319685039714717696,1319685039714717696,U.S. Attorney Scott W. Brady has appointed two...,False,"[0, 158]","{'hashtags': [], 'symbols': [], 'user_mentions...","<a href=""https://www.townnews.com/"" rel=""nofol...",NaN,NaN,NaN,NaN,None,"{'id': 42950890, 'id_str': '42950890', 'name':...",NaN,NaN,None,NaN,False,0,0,False,False,0.0,en,NaN,NaN,NaN,NaN,NaN
1,2020-10-23 17:00:55+00:00,1319685245369634817,1319685245369634816,People like that are the real problem. https:/...,False,"[0, 38]","{'hashtags': [], 'symbols': [], 'user_mentions...","<a href=""https://mobile.twitter.com"" rel=""nofo...",NaN,NaN,NaN,NaN,None,"{'id': 963327331, 'id_str': '963327331', 'name...",NaN,NaN,None,NaN,True,0,1,False,False,0.0,en,1.268518e+18,1.268518e+18,"{'url': 'https://t.co/8RrhF4LJ0b', 'expanded':...",{'created_at': 'Thu Jun 04 12:21:33 +0000 2020...,NaN
2,2020-10-23 17:01:25+00:00,1319685372109070336,1319685372109070336,@SteveHofstetter I think it will be close. Bid...,False,"[17, 257]","{'hashtags': [], 'symbols': [], 'user_mentions...","<a href=""http://twitter.com/download/android"" ...",1.319670e+18,1.319670e+18,1.597824e+07,1.597824e+07,SteveHofstetter,"{'id': 1255243669365538823, 'id_str': '1255243...",NaN,NaN,None,NaN,False,0,0,False,False,NaN,en,NaN,NaN,NaN,NaN,NaN
3,2020-10-23 17:01:47+00:00,1319685460923473921,1319685460923473920,"@EricHuseby4 @DFBHarvard i know, i know. Thats...",False,"[25, 178]","{'hashtags': [], 'symbols': [], 'user_mentions...","<a href=""https://mobile.twitter.com"" rel=""nofo...",1.319685e+18,1.319685e+18,1.217451e+18,1.217451e+18,EricHuseby4,"{'id': 582385180, 'id_str': '582385180', 'name...",NaN,NaN,None,NaN,False,0,0,False,False,NaN,en,NaN,NaN,NaN,NaN,NaN
4,2020-10-23 17:01:59+00:00,1319685512882434048,1319685512882434048,"@bblock29 His guilty plea.. guilty to 200,000+...",False,"[10, 243]","{'hashtags': [], 'symbols': [], 'user_mentions...","<a href=""http://twitter.com/download/iphone"" r...",1.319684e+18,1.319684e+18,1.949790e+09,1.949790e+09,bblock29,"{'id': 1280115505123209216, 'id_str': '1280115...",NaN,NaN,None,NaN,False,0,8,False,False,NaN,en,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2043,2020-10-23 23:55:09+00:00,1319789489418604544,1319789489418604544,Fraud is wrong no matter who commits it. But i...,False,"[0, 112]","{'hashtags': [], 'symbols': [], 'user_mentions...","<a href=""https://mobile.twitter.com"" rel=""nofo...",NaN,NaN,NaN,NaN,None,"{'id': 15586035, 'id_str': '15586035', 'name':...",NaN,NaN,None,NaN,True,0,0,False,False,0.0,en,1.319765e+18,1.319765e+18,"{'url': 'https://t.co/eSNPqHBCCQ', 'expanded':...",{'created_at': 'Fri Oct 23 22:17:08 +0000 2020...,NaN
2044,2020-10-23 23:50:03+00:00,1319788204363374593,1319788204363374592,@Danthefann @LasVegasLocally Sure. When she go...,False,"[29, 286]","{'hashtags': [], 'symbols': [], 'user_mentions...","<a href=""http://twitter.com/download/iphone"" r...",1.319778e+18,1.319778e+18,1.664026e+09,1.664026e+09,Danthefann,"{'id': 4627791, 'id_str': '4627791', 'name': '...",NaN,NaN,None,NaN,False,1,23,False,False,NaN,en,NaN,NaN,NaN,NaN,NaN
2045,2020-10-23 23:55:49+00:00,1319789657933123584,1319789657933123584,@PennCapitalStar @PaHouseDems @elizhardison Wh...,False,"[44, 298]","{'hashtags': [], 'symbols': [], 'user_mentions...","<a href=""https://mobile.twitter.com"" rel=""nofo...",1.319733e+18,1.319733e+18,1.083843e+18,1.083843e+18,PennCapitalStar,"{'id': 1054729040286892033, 'id_str': '1054729...",NaN,NaN,None,NaN,False,0,0,False,False,0.0,en,NaN,NaN,NaN,NaN,NaN
2046,2020-10-23 23:53:53+00:00,1319789169867186177,1319789169867186176,retweet retweet retweet https://t.co/e8pLNHVO9u,False,"[0, 23]","{'hashtags': [], 'symbols': [], 'user_mentions...","<a href=""https://mobile.twitter.com"" rel=""nofo...",NaN,NaN,NaN,NaN,None,"{'id': 1303987978025553920, 'id_str': '1303987...",NaN,NaN,None,NaN,True,0,0,False,False,0.0,en,1.317948e+18,1.317948e+18,"{'url': 'https://t.co/e8pLNHVO9u', 'expanded':...",NaN,NaN
2047,2020-10-23 23:59:25+00:00,1319790562011217922,1319790562011217920,@JoeBiden I feel Trump will cheat . I think R...,False,"[10, 259]","{'hashtags': [], 'symbols': [], 'user_mentions...","<a href=""http://twitter.com/download/iphone"" r...",1.319785e+18,1.319785e+18,9.390910e+05,9.390910e+05,JoeBiden,"{'id': 29818954, 'id_str': '29818954', 'name':...",NaN,NaN,None,NaN,False,0,6,False,False,NaN,en,NaN,NaN,NaN,NaN,NaN

In [23]:
import nltk
import sqlite3
import pandas as pd
pd.set_option('display.max_columns', None)
import csv
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import pickle
import collections
from mpl_toolkits.mplot3d import Axes3D

In [ ]:
conn = sqlite3.connect("tweets_data.db")
curr = conn.cursor()

In [ ]:
#users
file = pd.read_csv("/content/drive/MyDrive/HoyaHacks 2021/users1.csv")
file = file[["user_id", "user_active_status"]]
file

                    user_id  user_community user_active_status
0       1249546905849196545             0.0             active
1       1249547592150716416             0.0             active
2                  30802644             0.0             active
3       1249548061954670592             0.0             active
4                  30802842             0.0             active
...                     ...             ...                ...
499995   969913826647801856             3.0             active
499996   969914883096662016             4.0             active
499997   969915018207571968             0.0             active
499998   969915683986341888             0.0             active
499999   969917167360671745             1.0             active

[500000 rows x 3 columns]

In [ ]:
#october tweets
f = open("/content/drive/MyDrive/HoyaHacks 2021/Files Hoya/tweets_10.pkl", 'rb')
info = pickle.load(f)
info = pd.DataFrame(info)
print(info.columns)
info = info[["tweet_id", "user_active_status", "retweet_count_metadata","Date"]]
info

Index(['tweet_id', 'user_community', 'user_active_status',
       'retweet_count_metadata', 'quote_count_metadata',
       'retweet_count_by_community_0', 'quote_count_by_community_0',
       'retweet_count_by_community_1', 'quote_count_by_community_1',
       'retweet_count_by_community_2', 'quote_count_by_community_2',
       'retweet_count_by_community_3', 'quote_count_by_community_3',
       'retweet_count_by_community_4', 'quote_count_by_community_4',
       'retweet_count_by_suspended_users', 'quote_count_by_suspended_users',
       'Date'],
      dtype='object')

,tweet_id,user_active_status,retweet_count_metadata,Date
0,1319685030826938369,deleted,0,2020-10-23
1,1319685039714717696,active,0,2020-10-23
2,1319685089375158274,active,0,2020-10-23
3,1319685151031500801,suspended,0,2020-10-23
4,1319685176436396035,deleted,0,2020-10-23
...,...,...,...,...
25309,1322689735647731717,active,0,2020-10-31
25310,1322689780635848704,active,3,2020-10-31
25311,1322689790119010305,suspended,0,2020-10-31
25312,1322689806565081090,active,0,2020-10-31
25313,1322689806678269952,active,0,2020-10-31

In [ ]:
#october retweets
f = open("/content/drive/MyDrive/HoyaHacks 2021/Files Hoya/retweets_10.pkl", 'rb')
info = pickle.load(f)
info = pd.DataFrame(info)
print(info.columns)
#info = info[["tweet_id", "user_active_status", "user_community", "retweet_count_metadata","Date"]]
#info['user_community'] = info['user_community'].replace(np.nan, 0.0)
info

Index(['retweeted_id', 'user_id', 'Date'], dtype='object')

              retweeted_id              user_id       Date
0      1319609788091817985  1198035481650515974 2020-10-23
1      1319667770083233792   910642944293654528 2020-10-23
2      1319550613668175875            372053421 2020-10-23
3      1310647895033610240  1032786509995421696 2020-10-23
4      1319677395629006849            380671484 2020-10-23
...                    ...                  ...        ...
70761  1322575473373753344           4693108513 2020-10-31
70762  1322665920880353280   702890489981374464 2020-10-31
70763  1322581566569259015   946079315615240192 2020-10-31
70764  1322680088530505728            275765417 2020-10-31
70765  1322649784193183744   891491872945745921 2020-10-31

[700177 rows x 3 columns]

In [16]:
conn = sqlite3.connect("tweets_data.db")
cur = conn.cursor()
table_name = "nov_01"
cur.execute("DROP TABLE IF EXISTS " + table_name)
cur.execute("CREATE TABLE " + table_name +  " (retweeted_id INTEGER, user_id INTEGER);")

nov_01 = pd.read_csv("/content/drive/MyDrive/HoyaHacks 2021/2020-11-01.csv")
nov_01.to_sql("nov_01", conn, if_exists='append', index=False)

pd.read_sql('''SELECT * FROM nov_01 ORDER BY ROWID ASC LIMIT 10''', conn)
cur.execute("SELECT retweeted_id, COUNT(user_id) FROM nov_01 GROUP BY retweeted_id")
pd.read_sql('''SELECT retweeted_id, COUNT(user_id) FROM nov_01 GROUP BY retweeted_id ORDER BY COUNT(user_id) DESC LIMIT 100''', conn)


pd.read_sql('''SELECT user_id, COUNT(retweeted_id) FROM nov_01 GROUP BY user_id ORDER BY COUNT(retweeted_id) DESC LIMIT 100''', conn)

                user_id  COUNT(retweeted_id)
0    915221691881705473                   46
1             283677281                   32
2            1853047993                   31
3   1254536281696145410                   30
4   1280155609036398593                   29
..                  ...                  ...
95   846180912098430976                   10
96   862238681272385536                   10
97   910003499546566658                   10
98   948464246064427008                   10
99   986716551935016960                   10

[100 rows x 2 columns]

In [ ]:
https://stackoverflow.com/questions/7887011/how-to-drop-a-table-if-it-exists
https://stackoverflow.com/questions/1650946/mysql-create-table-if-not-exists-error-1050
https://www.sqlitetutorial.net/sqlite-create-table/
https://stackoverflow.com/questions/2887878/importing-a-csv-file-into-a-sqlite3-database-table-using-python
https://www.sqlitetutorial.net/sqlite-python/creating-database/
https://www.sqlitetutorial.net/sqlite-group-by/